import re,os
D='docs/research/sendero2-fmmarketingdigital-com-0ca8991d/root-8a5edab2'
MOB=os.path.join(D,'mobile'); SPEC=os.path.join(D,'components'); os.makedirs(SPEC,exist_ok=True)
NAME={'header':'SiteHeader','01-hero':'HeroSection','02-filosofia':'FilosofiaSection',
 '03-oferta':'OfertaSection','04-experiencia':'ExperienciaSection','05-noticias':'NoticiasSection',
 '06-podcast':'PodcastSection','07-cta':'CtaSection','footer':'SiteFooter'}

def decls(body):
    d={}
    for part in body.split(';'):
        if ':' in part:
            k,v=part.split(':',1); d[k.strip()]=v.strip()
    return d

for key,comp in NAME.items():
    s=open(os.path.join(MOB,key+'.md'),encoding='utf-8').read()
    basetxt=s.split('## BASE')[1].split('## MOBILE')[0]
    mobtxt=s.split('## MOBILE')[1]
    base={}
    for sel,body in re.findall(r'([^{}\n]+)\{([^{}]*)\}',basetxt):
        sel=sel.strip()
        if sel.startswith(('@','```')) or not sel: continue
        base.setdefault(sel,{}).update(decls(body))
    mob={}
    for sel,body in re.findall(r'([^{}\n]+)\{([^{}]*)\}',mobtxt):
        sel=sel.strip()
        if sel.startswith(('@','```')) or not sel: continue
        mob.setdefault(sel,{}).update(decls(body))

    diffs=[(sel,k,base.get(sel,{}).get(k,'<not set at desktop>'),v)
           for sel,d in mob.items() for k,v in d.items() if base.get(sel,{}).get(k)!=v]

    basecss='\n'.join('%s {\n  %s\n}'%(sel,'\n  '.join('%s: %s;'%(k,v) for k,v in d.items()))
                      for sel,d in base.items() if d)
    mobcss='\n'.join('  %s {\n    %s\n  }'%(sel,'\n    '.join('%s: %s;'%(k,v) for k,v in d.items()))
                     for sel,d in mob.items() if d)
    difftbl='\n'.join('| `%s` | `%s` | `%s` | `%s` |'%(sel,k,bv,mv) for sel,k,bv,mv in diffs)

    open(os.path.join(SPEC,comp+'.mobile-fix.spec.md'),'w',encoding='utf-8').write(f"""# {comp} — corrected desktop/mobile CSS

## Why this exists
The original spec you worked from was generated by a flawed extractor: it flattened
`@media (max-width: 478px)` rules into the base rule list. That made mobile rules look
like "later duplicates" of desktop rules. Wherever you merged those duplicates into the
base styles, **you applied mobile values at desktop**; wherever you guessed they were
mobile-only, you were right but had no way to confirm.

This file is the corrected, authoritative split. Media queries were stripped before
computing BASE, so BASE is true desktop and MOBILE is the only breakpoint.

## BASE — desktop, applies at ALL widths unless overridden below
```css
{basecss}
```

## MOBILE — `@media (max-width: 478px)`, the ONLY breakpoint on the whole site
```css
@media (max-width: 478px) {{
{mobcss}
}}
```

## Properties that genuinely CHANGE at 478px ({len(diffs)})
| selector | property | desktop | mobile |
|---|---|---|---|
{difftbl}
""")
    print(comp,'base_sel=%d mob_sel=%d diffs=%d'%(len(base),len(mob),len(diffs)))
